In [1]:
import os, re, glob, math, time, random
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image, ImageOps
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
import timm

import torchvision.transforms as T
from torchvision.transforms import InterpolationMode
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import f1_score
from tqdm import tqdm
from ultralytics import YOLO
import cv2

In [2]:
def seed_everything(seed):
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = False
    torch.backends.cudnn.benchmark = True
seed_everything(42)

In [3]:
DATA_DIR = Path(r"E:\multiview_pig_posture_recognition")
print("DATA_DIR:", DATA_DIR)
train_csv = DATA_DIR / (f"train1.csv")
train1_img_dir = DATA_DIR / "train1_images"

DATA_DIR: E:\multiview_pig_posture_recognition

Use photos taken in 20250209 as test

In [4]:
train_df = pd.read_csv(train_csv)
mask_test = train_df["image_id"].str.contains(r"_20250209_")
test_df = train_df.loc[mask_test].copy()
train_df = train_df.loc[~mask_test].copy()

In [5]:
train_df = train_df.sort_values("image_id")
classes_txt = DATA_DIR / "pig_posture_classes.txt"
with open(classes_txt, "r") as f:
        CLASS_NAMES = [line.strip() for line in f if line.strip()]
pd.DataFrame({
    "label": range(5),
    "class_name": CLASS_NAMES
})

   label           class_name
0      0   Lateral_lying_left
1      1  Lateral_lying_right
2      2              Sitting
3      3             Standing
4      4        Sternal_lying

In [6]:
def parse_cam_type(image_id: str):
    m = re.search(r"_([a-zA-Z]+)_cam\d+_", str(image_id))
    return m.group(1).lower() if m else "unk"
train_df["cam_type"] = train_df["image_id"].map(parse_cam_type)
test_df["cam_type"]  = test_df["image_id"].map(parse_cam_type)

In [7]:
def parse_bbox_string(bbox_str):
    s = str(bbox_str).strip()
    if s.startswith("[") and s.endswith("]"):
        s = s[1:-1].strip()
    s = s.replace(",", " ")
    parts = [p for p in s.split() if p]
    if len(parts) != 4:
        raise ValueError(f"Bad bbox: {bbox_str}")
    x, y, w, h = map(float, parts)
    return x, y, w, h

bx = train_df["bbox"].apply(parse_bbox_string)
train_df["x"] = bx.apply(lambda t: t[0])
train_df["y"] = bx.apply(lambda t: t[1])
train_df["w"] = bx.apply(lambda t: t[2])
train_df["h"] = bx.apply(lambda t: t[3])

bx = test_df["bbox"].apply(parse_bbox_string)
test_df["x"] = bx.apply(lambda t: t[0])
test_df["y"] = bx.apply(lambda t: t[1])
test_df["w"] = bx.apply(lambda t: t[2])
test_df["h"] = bx.apply(lambda t: t[3])

In [8]:
def parse_scene(image_id):
    parts = image_id.split("_")

    pen  = parts[0]        # pen1/pen2
    date = parts[3]        # 20250108 date

    return f"{pen}_{date}"

To avoid data leakage caused by short time window (e.g., two pictures taken in 10s successively), Any two images, provided that the time difference is less than 45 seconds and are both taken by the same camera , must be entered into the train or the val as a whole and cannot be separated.

In [9]:
train_df["datetime"] = pd.to_datetime(
    train_df["image_id"].str.extract(r'(\d{8}_\d{6})')[0],
    format="%Y%m%d_%H%M%S"
)
train_df = train_df.sort_values(["cam_type", "datetime"]).reset_index(drop=True)
time_threshold = 45  # time window
group_ids = []
current_group = 0

for cam in train_df["cam_type"].unique():

    cam_idx = train_df["cam_type"] == cam
    cam_df = train_df[cam_idx]

    last_time = None

    for idx in cam_df.index:
        current_time = train_df.loc[idx, "datetime"]
        if last_time is None:
            group_ids.append(current_group)
        else:
            diff = (current_time - last_time).total_seconds()
            if diff <= time_threshold:
                group_ids.append(current_group)
            else:
                current_group += 1
                group_ids.append(current_group)

        last_time = current_time

    current_group += 1

train_df["time_group"] = group_ids

In [10]:
img_dom = (
    train_df
    .groupby("image_id") # avoid data leakage, separate pictures, instead of patch into train/test
    .agg(dom_label=("class_id", lambda s: s.value_counts().idxmax()), # select the largest class group to represent the picture
         cam_type=("cam_type", "first"), # a picture is taken by a specific angle, which means that the camera type should be identical
            time_group=("time_group", "first"))
    .reset_index()
)

img_dom["scene_time_group"] = (
    img_dom["cam_type"].astype(str)
    + "_"
    + img_dom["time_group"].astype(str)
)

In [11]:
from sklearn.model_selection import StratifiedGroupKFold
train_df_new = []
val_df_new =[]
sgkf = StratifiedGroupKFold(
    n_splits=2,
    shuffle=True,
    random_state=42
)

splits = list(
    sgkf.split(
        img_dom,
        y=img_dom["dom_label"], # This tells the splitter to maintain the class distribution of dom_label across the folds.
        groups=img_dom["scene_time_group"] # all samples belonging to the same group are assigned to the same fold.
    )
)

train_idx, val_idx = splits[0]

train_imgs = set(img_dom.iloc[train_idx]["image_id"])
val_imgs   = set(img_dom.iloc[val_idx]["image_id"])

train_df_new = train_df[train_df["image_id"].isin(train_imgs)].reset_index(drop=True)
val_df_new   = train_df[train_df["image_id"].isin(val_imgs)].reset_index(drop=True)

E:\multiview_pig_posture_recognition\.venv3\lib\site-packages\sklearn\model_selection\_split.py:1035: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(

In [12]:
print("train:", train_df_new.shape, "test:", test_df.shape, "val:", val_df_new.shape)

train: (16678, 13) test: (1744, 11) val: (4512, 13)

In [13]:
def resolve_train_image_path(image_id: str):
    p1 = train1_img_dir / image_id
    if p1.exists(): return p1
    hits = glob.glob(str(DATA_DIR / "**" / str(image_id)), recursive=True)
    if hits: return Path(hits[0])
    raise FileNotFoundError(f"Train image not found: {image_id}")

def resolve_test_image_path(image_id: str):
    p = train1_img_dir / image_id
    if p.exists(): return p
    hits = glob.glob(str(DATA_DIR / "**" / str(image_id)), recursive=True)
    if hits: return Path(hits[0])
    raise FileNotFoundError(f"Test image not found: {image_id}")

In [14]:
train_df_new.head()

,row_id,image_id,width,height,bbox,class_id,cam_type,x,y,w,h,datetime,time_group
0,train_pen1_orb_cam2_20250108_080108_0004,pen1_orb_cam2_20250108_080108.jpg,1920,1080,"[817.7,0.0,262.0,264.3]",3,orb,817.7,0.0,262.0,264.3,2025-01-08 08:01:08,0
1,train_pen1_orb_cam2_20250108_080108_0005,pen1_orb_cam2_20250108_080108.jpg,1920,1080,"[428.0,416.0,243.0,433.0]",4,orb,428.0,416.0,243.0,433.0,2025-01-08 08:01:08,0
2,train_pen1_orb_cam2_20250108_080108_0002,pen1_orb_cam2_20250108_080108.jpg,1920,1080,"[1204.5,4.0,209.0,296.0]",3,orb,1204.5,4.0,209.0,296.0,2025-01-08 08:01:08,0
3,train_pen1_orb_cam2_20250108_080108_0000,pen1_orb_cam2_20250108_080108.jpg,1920,1080,"[987.0,314.5,447.0,472.0]",3,orb,987.0,314.5,447.0,472.0,2025-01-08 08:01:08,0
4,train_pen1_orb_cam2_20250108_080108_0001,pen1_orb_cam2_20250108_080108.jpg,1920,1080,"[559.5,199.0,296.0,417.0]",3,orb,559.5,199.0,296.0,417.0,2025-01-08 08:01:08,0

# pig  bbox regression (yolo)

## yolo

In [18]:
def convert_to_yolo(df):

    df = df.copy()

    df["x_center"] = (df["x"] + df["w"]/2) / df["width"]
    df["y_center"] = (df["y"] + df["h"]/2) / df["height"]
    df["w_norm"] = df["w"] / df["width"]
    df["h_norm"] = df["h"] / df["height"]

    return df

In [19]:
def write_yolo_labels(df, label_dir):

    Path(label_dir).mkdir(parents=True, exist_ok=True)

    for img_id, group in df.groupby("image_id"):

        label_path = Path(label_dir) / img_id.replace(".jpg", ".txt")

        with open(label_path, "w") as f:
            for _, row in group.iterrows():

                line = f"{row.class_id} {row.x_center} {row.y_center} {row.w_norm} {row.h_norm}\n"
                f.write(line)

In [21]:
import shutil
def copy_images(df, src_dir, dst_dir):

    Path(dst_dir).mkdir(parents=True, exist_ok=True)

    for img in df["image_id"].unique():

        src = src_dir / img
        dst = Path(dst_dir) / img

        if src.exists():
            shutil.copy(src, dst)

In [22]:
train_df = convert_to_yolo(train_df_new)
val_df = convert_to_yolo(val_df_new)
test_df = convert_to_yolo(test_df)

write_yolo_labels(train_df, "dataset/labels/train")
write_yolo_labels(val_df, "dataset/labels/val")
write_yolo_labels(test_df, "dataset/labels/test")

copy_images(train_df, train1_img_dir, "dataset/images/train")
copy_images(val_df, train1_img_dir, "dataset/images/val")
copy_images(test_df, train1_img_dir, "dataset/images/test")

AdamW(lr=0.001111, momentum=0.9)
Let yolo decide the best parameter

In [2]:
model = YOLO("yolov8n.pt")

model.train(
    data="data.yaml",
    epochs=10,
    imgsz=640,
    name="yolo_exp16"
)

Ultralytics 8.4.19  Python-3.10.11 torch-2.12.0.dev20260224+cu128 CUDA:0 (NVIDIA GeForce RTX 5060 Laptop GPU, 8151MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=10, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolo_exp16, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=E:\multiview_pig_posture_recognition\runs\detect\yolo_exp16, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=5

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    752287  ultralytics.nn.modules.head.Detect           [5, 16, None, [64, 128, 256]]
Model summary: 130 layers, 3,011,823 parameters, 3,011,807 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.00.0 ms, read: 1761.5718.1 MB/s, size: 249.8 KB)
train: Scanning E:\multiview_pig_posture_recognition\dataset\labels\train... 2339 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 2339/2339 2.4Kit/s 1.0s0.1s
train: New cache created: E:\multiview_pig_posture_recognition\dataset\labels\train.cache
val: Fast image access  (ping: 0.10.0 ms, read: 53.730.3 MB/s, size: 406.9 KB)
val: Scanning E:\multiview_pig_posture_recognition\dataset\labels\val... 557 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 557/557 533.2it/s 1.0s0.0s
val: New cache created: E:\multiview_pig_posture_recognition\dataset\labels\val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001111, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to E:\multiview_pig_posture_recognition\runs\detect\yolo_exp16\labels.jpg...
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to E:\multiview_pig_posture_recognition\runs\detect\yolo_exp16
Starting training for 10 epochs...
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/10      2.21G     0.6199      1.794     0.9578         24        640: 100% ━━━━━━━━━━━━ 147/147 2.2it/s 1:080.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 3.8it/s 4.7s0.2s
                   all        557       4512       0.42      0.617      0.445      0.376

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/10      2.22G     0.5354      1.017     0.8867         22        640: 100% ━━━━━━━━━━━━ 147/147 7.6it/s 19.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 6.5it/s 2.8s0.2s
                   all        557       4512      0.533      0.585      0.528      0.455

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/10      2.22G     0.5098     0.8668     0.8733         22        640: 100% ━━━━━━━━━━━━ 147/147 9.0it/s 16.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 6.6it/s 2.7s0.2s
                   all        557       4512      0.536      0.684      0.602      0.515

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/10      2.22G     0.4813     0.7503     0.8596         19        640: 100% ━━━━━━━━━━━━ 147/147 8.4it/s 17.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 6.8it/s 2.6s0.2s
                   all        557       4512      0.586      0.629      0.661      0.581

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/10      2.22G     0.4472     0.6579     0.8512         21        640: 100% ━━━━━━━━━━━━ 147/147 9.2it/s 15.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 6.9it/s 2.6s0.2s
                   all        557       4512      0.759      0.616      0.652      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/10      2.22G      0.428     0.5939     0.8444         19        640: 100% ━━━━━━━━━━━━ 147/147 8.4it/s 17.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 7.0it/s 2.6s0.2s
                   all        557       4512      0.631      0.702      0.715      0.637

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/10      2.22G     0.4083     0.5327     0.8386         20        640: 100% ━━━━━━━━━━━━ 147/147 9.1it/s 16.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 7.2it/s 2.5s0.2s
                   all        557       4512      0.699      0.695       0.73      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/10      2.22G     0.3881      0.484     0.8312         22        640: 100% ━━━━━━━━━━━━ 147/147 9.3it/s 15.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 7.4it/s 2.4s0.2s
                   all        557       4512      0.695      0.721      0.754      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/10      2.22G     0.3743     0.4468     0.8258         19        640: 100% ━━━━━━━━━━━━ 147/147 9.3it/s 15.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 7.4it/s 2.4s0.1s
                   all        557       4512      0.758       0.71      0.777      0.707

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/10      2.22G     0.3568     0.4142     0.8245         17        640: 100% ━━━━━━━━━━━━ 147/147 9.2it/s 15.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 7.4it/s 2.4s0.1s
                   all        557       4512      0.751      0.766      0.814      0.748

10 epochs completed in 0.085 hours.
Optimizer stripped from E:\multiview_pig_posture_recognition\runs\detect\yolo_exp16\weights\last.pt, 6.2MB
Optimizer stripped from E:\multiview_pig_posture_recognition\runs\detect\yolo_exp16\weights\best.pt, 6.2MB

Validating E:\multiview_pig_posture_recognition\runs\detect\yolo_exp16\weights\best.pt...
Ultralytics 8.4.19  Python-3.10.11 torch-2.12.0.dev20260224+cu128 CUDA:0 (NVIDIA GeForce RTX 5060 Laptop GPU, 8151MiB)
Model summary (fused): 73 layers, 3,006,623 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 5.3it/s 3.4s0.2s
                   all        557       4512       0.76      0.759      0.814      0.747
    Lateral_lying_left        376        741      0.756      0.889      0.912      0.841
   Lateral_lying_right        327        659      0.827       0.86      0.913      0.839
               Sitting         82         91      0.458      0.242      0.361      0.327
              Standing        531       1757      0.951      0.962      0.987       0.91
         Sternal_lying        499       1264      0.808      0.844      0.898       0.82
Speed: 0.1ms preprocess, 0.7ms inference, 0.0ms loss, 1.0ms postprocess per image
Results saved to E:\multiview_pig_posture_recognition\runs\detect\yolo_exp16

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3, 4])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x0000020AC081C730>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,     0.22561,     0.19893,           0],
       [          1,           1,           1, ...,     0.29128,     0.23756,           0],
       [          1,           1,           1, ...,    0.037603,    0.037603,           0],
       [          1,           1,           1, ...,     0.32846,    0.099805,           0],
       [          1,           1,           1, ...,     0.16935,    0.086489,           0]], shape=(5, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,

## SSD

In [15]:
train_df_new["xmin"] = train_df_new["x"]
train_df_new["ymin"] = train_df_new["y"]
train_df_new["xmax"] = train_df_new["x"] + train_df_new["w"]
train_df_new["ymax"] = train_df_new["y"] + train_df_new["h"]

In [16]:
test_df["xmin"] = test_df["x"]
test_df["ymin"] = test_df["y"]
test_df["xmax"] = test_df["x"] + test_df["w"]
test_df["ymax"] = test_df["y"] + test_df["h"]

In [17]:
val_df_new["xmin"] = val_df_new["x"]
val_df_new["ymin"] = val_df_new["y"]
val_df_new["xmax"] = val_df_new["x"] + val_df_new["w"]
val_df_new["ymax"] = val_df_new["y"] + val_df_new["h"]

In [18]:
import torchvision
class PigDataset(torch.utils.data.Dataset):

    def __init__(self, df, img_dir, transforms=None):
        self.df = df
        self.img_dir = img_dir
        self.transforms = transforms
        self.image_ids = df.image_id.unique()

    def __getitem__(self, idx):

        image_id = self.image_ids[idx]
        records = self.df[self.df.image_id == image_id]

        img_path = os.path.join(self.img_dir, image_id)

        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        boxes = records[["xmin","ymin","xmax","ymax"]].values
        labels = records["class_id"].values + 1

        boxes = torch.as_tensor(boxes, dtype=torch.float32)
        labels = torch.as_tensor(labels, dtype=torch.int64)

        target = {
            "boxes": boxes,
            "labels": labels
        }

        if self.transforms:
            img = self.transforms(img)
        else:
            img = torchvision.transforms.ToTensor()(img)

        return img, target

    def __len__(self):
        return len(self.image_ids)

In [19]:
num_classes = 6   # 5 posture + background

model = torchvision.models.detection.ssd300_vgg16(
    weights="DEFAULT"
)

model.head.classification_head.num_classes = num_classes

Downloading: "https://download.pytorch.org/models/ssd300_vgg16_coco-b556d3b4.pth" to C:\Users\chenk/.cache\torch\hub\checkpoints\ssd300_vgg16_coco-b556d3b4.pth

100%|██████████| 136M/136M [00:02<00:00, 62.0MB/s]

In [26]:
train_dataset = PigDataset(
    train_df_new,
    train1_img_dir
)
train_loader = DataLoader(
    train_dataset,
    batch_size=4,
    shuffle=True,
    collate_fn=lambda x: tuple(zip(*x))
)

In [27]:
device = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)

In [28]:
params = [p for p in model.parameters() if p.requires_grad]

optimizer = torch.optim.AdamW(
    params,
    lr=0.001111,
    weight_decay=0.0005
)

In [29]:
num_epochs = 5

for epoch in range(num_epochs):
    model.train()
    epoch_loss = 0
    progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}")
    for images, targets in progress_bar:
        images = [img.to(device) for img in images]
        targets = [
            {k: v.to(device) for k, v in t.items()}
            for t in targets
        ]
        loss_dict = model(images, targets)
        loss = sum(loss_dict.values())
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
        progress_bar.set_postfix(
            loss=loss.item()
        )
    print("Epoch loss:", epoch_loss / len(train_loader))

Epoch 1/5: 100%|██████████| 585/585 [02:55<00:00,  3.33it/s, loss=5.17]

Epoch loss: 6.215165045322516

Epoch 2/5: 100%|██████████| 585/585 [01:39<00:00,  5.89it/s, loss=3.15]

Epoch loss: 4.511548455556234

Epoch 3/5: 100%|██████████| 585/585 [01:36<00:00,  6.05it/s, loss=2.62]

Epoch loss: 3.9766503574501755

Epoch 4/5: 100%|██████████| 585/585 [01:38<00:00,  5.92it/s, loss=3.12]

Epoch loss: 3.45458534089928

Epoch 5/5: 100%|██████████| 585/585 [01:36<00:00,  6.08it/s, loss=3.34]

Epoch loss: 3.0084034852492505

In [30]:
torch.save(model.state_dict(), "ssd_pig_model.pth")

# IoU（Intersection over Union）

## SSD

In [67]:
model = torchvision.models.detection.ssd300_vgg16(weights=None)
model.load_state_dict(torch.load("ssd_pig_model.pth"))

model = model.to(device)
model.eval()

SSD(
  (backbone): SSDFeatureExtractorVGG(
    (features): Sequential(
      (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU(inplace=True)
      (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU(inplace=True)
      (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (6): ReLU(inplace=True)
      (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (8): ReLU(inplace=True)
      (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (11): ReLU(inplace=True)
      (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (13): ReLU(inplace=True)
      (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (15): ReLU(inplace=True)
      (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=True)
      (17): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (18): ReLU(inplace=True)
      (19): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (20): ReLU(inplace=True)
      (21): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (22): ReLU(inplace=True)
    )
    (extra): ModuleList(
      (0): Sequential(
        (0): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
        (1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (2): ReLU(inplace=True)
        (3): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (4): ReLU(inplace=True)
        (5): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (6): ReLU(inplace=True)
        (7): Sequential(
          (0): MaxPool2d(kernel_size=3, stride=1, padding=1, dilation=1, ceil_mode=False)
          (1): Conv2d(512, 1024, kernel_size=(3, 3), stride=(1, 1), padding=(6, 6), dilation=(6, 6))
          (2): ReLU(inplace=True)
          (3): Conv2d(1024, 1024, kernel_size=(1, 1), stride=(1, 1))
          (4): ReLU(inplace=True)
        )
      )
      (1): Sequential(
        (0): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1))
        (1): ReLU(inplace=True)
        (2): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (3): ReLU(inplace=True)
      )
      (2): Sequential(
        (0): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1))
        (1): ReLU(inplace=True)
        (2): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (3): ReLU(inplace=True)
      )
      (3-4): 2 x Sequential(
        (0): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1))
        (1): ReLU(inplace=True)
        (2): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1))
        (3): ReLU(inplace=True)
      )
    )
  )
  (anchor_generator): DefaultBoxGenerator(aspect_ratios=[[2], [2, 3], [2, 3], [2, 3], [2], [2]], clip=True, scales=[0.07, 0.15, 0.33, 0.51, 0.69, 0.87, 1.05], steps=[8, 16, 32, 64, 100, 300])
  (head): SSDHead(
    (classification_head): SSDClassificationHead(
      (module_list): ModuleList(
        (0): Conv2d(512, 364, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (1): Conv2d(1024, 546, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (2): Conv2d(512, 546, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (3): Conv2d(256, 546, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (4-5): 2 x Conv2d(256, 364, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      )
    )
    (regression_head): SSDRegressionHead(
      (module_list): ModuleList(
        (0): Conv2d(512, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (1): Conv2d(1024, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (2): Conv2d(512, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (3): Conv2d(256, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (4-5): 2 x Conv2d(256, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      )
    )
  )
  (transform): GeneralizedRCNNTransform(
      Normalize(mean=[0.48235, 0.45882, 0.40784], std=[0.00392156862745098, 0.00392156862745098, 0.00392156862745098])
      Resize(min_size=(300,), max_size=300, mode='bilinear')
  )
)

In [71]:
import cv2
image_id = test_df["image_id"].iloc[0]
print(image_id)
img_path = train1_img_dir / image_id
img = cv2.imread(str(img_path))
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

img_tensor = torch.from_numpy(img).permute(2,0,1).float()/255
img_tensor = img_tensor.to(device)

model.eval()

with torch.no_grad():
    outputs = model([img_tensor])

pred_boxes = outputs[0]["boxes"].cpu().numpy()
scores = outputs[0]["scores"].cpu().numpy()
labels = outputs[0]["labels"].cpu().numpy()

pen2_tur_cam1_20250209_070148.jpg

In [72]:
pred_boxes = outputs[0]["boxes"].cpu().numpy()
scores = outputs[0]["scores"].cpu().numpy()
img_gt = img.copy()

for _, row in gt.iterrows():

    x1 = int(row["x"])
    y1 = int(row["y"])
    x2 = int(row["x"] + row["w"])
    y2 = int(row["y"] + row["h"])

    cv2.rectangle(
        img_gt,
        (x1, y1),
        (x2, y2),
        (0,255,0),   # green
        2
    )
img_pred = img_gt.copy()

for box, score in zip(pred_boxes, scores):

    if score < 0.5:
        continue

    x1, y1, x2, y2 = map(int, box)

    cv2.rectangle(
        img_pred,
        (x1, y1),
        (x2, y2),
        (255,0,0),  # red
        2
    )

In [73]:
from matplotlib.patches import Patch

plt.figure(figsize=(8,6))

plt.imshow(img_pred)
plt.axis("off")

legend_elements = [
    Patch(facecolor='none', edgecolor='green', label='Ground Truth'),
    Patch(facecolor='none', edgecolor='red', label='SSD Prediction')
]

plt.legend(
    handles=legend_elements,
    loc="upper right",
    frameon=True
)

plt.show()

In [74]:
def iou_xyxy(boxA, boxB):

    xA = max(boxA[0], boxB[0])
    yA = max(boxA[1], boxB[1])
    xB = min(boxA[2], boxB[2])
    yB = min(boxA[3], boxB[3])

    inter_w = max(0, xB - xA)
    inter_h = max(0, yB - yA)
    inter = inter_w * inter_h

    areaA = (boxA[2] - boxA[0]) * (boxA[3] - boxA[1])
    areaB = (boxB[2] - boxB[0]) * (boxB[3] - boxB[1])

    union = areaA + areaB - inter

    return inter / union if union > 0 else 0

In [75]:
gt_boxes = []

for _, row in gt.iterrows():

    x1 = row["x"]
    y1 = row["y"]
    x2 = row["x"] + row["w"]
    y2 = row["y"] + row["h"]

    gt_boxes.append([x1, y1, x2, y2])

In [91]:
score_threshold = 0.5

filtered_pred_boxes = []
for box, score in zip(pred_boxes, scores):
    if score >= score_threshold:
        filtered_pred_boxes.append(box)

In [92]:
ious = []

for pbox in filtered_pred_boxes:
    for gtbox in gt_boxes:

        iou = iou_xyxy(pbox, gtbox)
        ious.append(iou)

In [93]:
import numpy as np
mean_iou = np.mean(ious)
print("Mean IoU:", mean_iou)

Mean IoU: 0.07890809

## Yolo

In [62]:
%matplotlib notebook

In [46]:
image_id = test_df["image_id"].iloc[0]
print(image_id)

pen2_tur_cam1_20250209_070148.jpg

use one image as example

In [47]:
import cv2
import matplotlib.pyplot as plt

img_path = train1_img_dir / image_id

img = cv2.imread(str(img_path))
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

In [48]:
gt = test_df[test_df["image_id"] == image_id]

In [49]:
img_gt = img.copy()

for _, row in gt.iterrows():

    x1 = int(row["x"])
    y1 = int(row["y"])
    x2 = int(row["x"] + row["w"])
    y2 = int(row["y"] + row["h"])

    cv2.rectangle(
        img_gt,
        (x1, y1),
        (x2, y2),
        (0,255,0),   # green
        2
    )

In [50]:
model = YOLO("runs/detect/yolo_exp16/weights/best.pt")

In [51]:
results = model(str(img_path))

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_070148.jpg: 384x640 8 Standings, 1 Sternal_lying, 583.5ms
Speed: 2.4ms preprocess, 583.5ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)

In [52]:
pred_boxes = results[0].boxes.xyxy.cpu().numpy()
img_pred = img_gt.copy()

for box in pred_boxes:

    x1, y1, x2, y2 = map(int, box)

    cv2.rectangle(
        img_pred,
        (x1,y1),
        (x2,y2),
        (255,0,0),  # red
        2
    )

In [53]:
from matplotlib.patches import Patch
fig = plt.figure()

plt.imshow(img_pred)
plt.axis("off")

legend_elements = [
    Patch(facecolor='none', edgecolor='green', label='Ground Truth'),
    Patch(facecolor='none', edgecolor='red', label='YOLO Prediction')
]

plt.legend(
    handles=legend_elements,
    loc="upper right",
    frameon=True
)

plt.subplots_adjust(left=0, right=1, top=1, bottom=0)
plt.show()

In [54]:
def compute_iou(box1, box2):

    x1 = max(box1[0], box2[0])
    y1 = max(box1[1], box2[1])
    x2 = min(box1[2], box2[2])
    y2 = min(box1[3], box2[3])

    inter = max(0, x2-x1) * max(0, y2-y1)

    area1 = (box1[2]-box1[0]) * (box1[3]-box1[1])
    area2 = (box2[2]-box2[0]) * (box2[3]-box2[1])

    union = area1 + area2 - inter

    if union == 0:
        return 0

    return inter / union

In [28]:

image_ids = test_df["image_id"].unique()
ious = []

In [29]:
for image_id in image_ids:
    img_path = train1_img_dir / image_id
    results = model(str(img_path))
    pred_boxes = results[0].boxes.xyxy.cpu().numpy()

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_070148.jpg: 384x640 8 Standings, 1 Sternal_lying, 7.8ms
Speed: 2.3ms preprocess, 7.8ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_070508.jpg: 384x640 7 Standings, 2 Sternal_lyings, 7.3ms
Speed: 1.8ms preprocess, 7.3ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_070648.jpg: 384x640 1 Lateral_lying_left, 8 Standings, 1 Sternal_lying, 8.9ms
Speed: 1.8ms preprocess, 8.9ms inference, 2.4ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_071008.jpg: 384x640 1 Lateral_lying_left, 1 Lateral_lying_right, 6 Standings, 3 Sternal_lyings, 8.6ms
Speed: 1.6ms preprocess, 8.6ms inference, 2.9ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_071148.jpg: 384x640 1 Sitting, 6 Standings, 2 Sternal_lyings, 6.4ms
Speed: 1.6ms preprocess, 6.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_071509.jpg: 384x640 7 Standings, 2 Sternal_lyings, 8.2ms
Speed: 1.5ms preprocess, 8.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_071649.jpg: 384x640 1 Lateral_lying_left, 6 Standings, 3 Sternal_lyings, 8.1ms
Speed: 1.7ms preprocess, 8.1ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_072009.jpg: 384x640 1 Lateral_lying_right, 1 Sitting, 8 Standings, 1 Sternal_lying, 7.2ms
Speed: 1.9ms preprocess, 7.2ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_072149.jpg: 384x640 1 Lateral_lying_left, 1 Lateral_lying_right, 7 Standings, 2 Sternal_lyings, 7.5ms
Speed: 1.9ms preprocess, 7.5ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_072509.jpg: 384x640 1 Lateral_lying_left, 8 Standings, 7.1ms
Speed: 1.7ms preprocess, 7.1ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_072649.jpg: 384x640 1 Sitting, 8 Standings, 1 Sternal_lying, 9.9ms
Speed: 2.0ms preprocess, 9.9ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_073009.jpg: 384x640 2 Lateral_lying_lefts, 7 Standings, 1 Sternal_lying, 8.9ms
Speed: 1.9ms preprocess, 8.9ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_073150.jpg: 384x640 3 Lateral_lying_lefts, 2 Lateral_lying_rights, 5 Standings, 5.7ms
Speed: 1.7ms preprocess, 5.7ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_073510.jpg: 384x640 4 Lateral_lying_lefts, 3 Standings, 3 Sternal_lyings, 5.5ms
Speed: 1.5ms preprocess, 5.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_073650.jpg: 384x640 5 Lateral_lying_lefts, 1 Lateral_lying_right, 3 Standings, 1 Sternal_lying, 10.1ms
Speed: 1.9ms preprocess, 10.1ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_074010.jpg: 384x640 2 Lateral_lying_lefts, 1 Lateral_lying_right, 4 Standings, 2 Sternal_lyings, 6.7ms
Speed: 1.7ms preprocess, 6.7ms inference, 2.4ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_074150.jpg: 384x640 2 Lateral_lying_lefts, 1 Lateral_lying_right, 5 Standings, 1 Sternal_lying, 9.4ms
Speed: 1.8ms preprocess, 9.4ms inference, 2.4ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_074510.jpg: 384x640 1 Sitting, 4 Standings, 3 Sternal_lyings, 7.0ms
Speed: 1.8ms preprocess, 7.0ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_074651.jpg: 384x640 4 Standings, 5 Sternal_lyings, 7.2ms
Speed: 1.5ms preprocess, 7.2ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_075011.jpg: 384x640 2 Lateral_lying_lefts, 4 Standings, 5 Sternal_lyings, 9.1ms
Speed: 1.6ms preprocess, 9.1ms inference, 2.2ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_075151.jpg: 384x640 3 Lateral_lying_lefts, 1 Lateral_lying_right, 4 Standings, 3 Sternal_lyings, 9.6ms
Speed: 2.2ms preprocess, 9.6ms inference, 2.2ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_075511.jpg: 384x640 3 Lateral_lying_lefts, 1 Lateral_lying_right, 3 Standings, 3 Sternal_lyings, 5.4ms
Speed: 1.4ms preprocess, 5.4ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_075652.jpg: 384x640 3 Lateral_lying_lefts, 2 Lateral_lying_rights, 2 Standings, 3 Sternal_lyings, 9.9ms
Speed: 1.5ms preprocess, 9.9ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_080012.jpg: 384x640 3 Lateral_lying_lefts, 1 Lateral_lying_right, 2 Standings, 4 Sternal_lyings, 8.9ms
Speed: 1.4ms preprocess, 8.9ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_080152.jpg: 384x640 5 Lateral_lying_lefts, 1 Lateral_lying_right, 1 Standing, 4 Sternal_lyings, 5.2ms
Speed: 1.7ms preprocess, 5.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_080512.jpg: 384x640 4 Lateral_lying_lefts, 4 Lateral_lying_rights, 1 Standing, 2 Sternal_lyings, 5.2ms
Speed: 1.6ms preprocess, 5.2ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_080652.jpg: 384x640 4 Lateral_lying_lefts, 4 Lateral_lying_rights, 1 Standing, 2 Sternal_lyings, 9.3ms
Speed: 1.5ms preprocess, 9.3ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_081012.jpg: 384x640 3 Lateral_lying_lefts, 4 Lateral_lying_rights, 1 Standing, 2 Sternal_lyings, 7.8ms
Speed: 2.0ms preprocess, 7.8ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_081152.jpg: 384x640 4 Lateral_lying_lefts, 3 Lateral_lying_rights, 1 Standing, 2 Sternal_lyings, 5.1ms
Speed: 1.5ms preprocess, 5.1ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_081512.jpg: 384x640 6 Lateral_lying_lefts, 3 Lateral_lying_rights, 2 Sternal_lyings, 10.3ms
Speed: 1.8ms preprocess, 10.3ms inference, 2.9ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_081653.jpg: 384x640 5 Lateral_lying_lefts, 3 Lateral_lying_rights, 3 Sternal_lyings, 8.0ms
Speed: 1.8ms preprocess, 8.0ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_082013.jpg: 384x640 6 Lateral_lying_lefts, 3 Lateral_lying_rights, 1 Sternal_lying, 5.4ms
Speed: 1.5ms preprocess, 5.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_082153.jpg: 384x640 6 Lateral_lying_lefts, 3 Lateral_lying_rights, 2 Sternal_lyings, 5.1ms
Speed: 1.5ms preprocess, 5.1ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_082513.jpg: 384x640 7 Lateral_lying_lefts, 1 Lateral_lying_right, 3 Sternal_lyings, 9.3ms
Speed: 1.8ms preprocess, 9.3ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_082653.jpg: 384x640 5 Lateral_lying_lefts, 3 Lateral_lying_rights, 1 Standing, 2 Sternal_lyings, 6.6ms
Speed: 1.6ms preprocess, 6.6ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_083013.jpg: 384x640 1 Lateral_lying_left, 2 Sittings, 7 Standings, 1 Sternal_lying, 5.2ms
Speed: 1.5ms preprocess, 5.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_083154.jpg: 384x640 9 Standings, 8.3ms
Speed: 1.7ms preprocess, 8.3ms inference, 2.7ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_083514.jpg: 384x640 8 Standings, 1 Sternal_lying, 8.1ms
Speed: 1.6ms preprocess, 8.1ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_083654.jpg: 384x640 1 Lateral_lying_left, 7 Standings, 2 Sternal_lyings, 9.6ms
Speed: 1.9ms preprocess, 9.6ms inference, 2.4ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_084014.jpg: 384x640 7 Standings, 2 Sternal_lyings, 6.8ms
Speed: 1.8ms preprocess, 6.8ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_084154.jpg: 384x640 7 Standings, 2 Sternal_lyings, 9.1ms
Speed: 1.6ms preprocess, 9.1ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_084515.jpg: 384x640 3 Lateral_lying_lefts, 1 Sitting, 6 Standings, 2 Sternal_lyings, 9.4ms
Speed: 1.7ms preprocess, 9.4ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_084655.jpg: 384x640 4 Lateral_lying_lefts, 4 Standings, 2 Sternal_lyings, 11.2ms
Speed: 1.4ms preprocess, 11.2ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_085015.jpg: 384x640 5 Lateral_lying_lefts, 3 Standings, 3 Sternal_lyings, 6.1ms
Speed: 1.7ms preprocess, 6.1ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_085155.jpg: 384x640 5 Lateral_lying_lefts, 2 Lateral_lying_rights, 2 Standings, 1 Sternal_lying, 6.4ms
Speed: 1.7ms preprocess, 6.4ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_085515.jpg: 384x640 5 Lateral_lying_lefts, 1 Lateral_lying_right, 3 Standings, 1 Sternal_lying, 6.0ms
Speed: 1.6ms preprocess, 6.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_085655.jpg: 384x640 4 Lateral_lying_lefts, 2 Sittings, 3 Standings, 2 Sternal_lyings, 5.1ms
Speed: 1.4ms preprocess, 5.1ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_090015.jpg: 384x640 5 Lateral_lying_lefts, 1 Sitting, 3 Standings, 2 Sternal_lyings, 9.5ms
Speed: 1.5ms preprocess, 9.5ms inference, 2.8ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_090156.jpg: 384x640 5 Lateral_lying_lefts, 2 Standings, 3 Sternal_lyings, 7.3ms
Speed: 1.7ms preprocess, 7.3ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_090516.jpg: 384x640 2 Lateral_lying_lefts, 1 Lateral_lying_right, 1 Sitting, 2 Standings, 3 Sternal_lyings, 7.1ms
Speed: 1.6ms preprocess, 7.1ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_090656.jpg: 384x640 4 Lateral_lying_lefts, 2 Lateral_lying_rights, 2 Sittings, 3 Standings, 3 Sternal_lyings, 6.0ms
Speed: 2.0ms preprocess, 6.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_091016.jpg: 384x640 3 Lateral_lying_lefts, 2 Lateral_lying_rights, 2 Standings, 3 Sternal_lyings, 5.4ms
Speed: 1.4ms preprocess, 5.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_091156.jpg: 384x640 5 Lateral_lying_lefts, 3 Lateral_lying_rights, 1 Standing, 3 Sternal_lyings, 6.1ms
Speed: 1.5ms preprocess, 6.1ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_091516.jpg: 384x640 6 Lateral_lying_lefts, 4 Lateral_lying_rights, 1 Standing, 1 Sternal_lying, 7.6ms
Speed: 1.7ms preprocess, 7.6ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_091657.jpg: 384x640 7 Lateral_lying_lefts, 1 Lateral_lying_right, 1 Standing, 1 Sternal_lying, 6.1ms
Speed: 1.8ms preprocess, 6.1ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_092017.jpg: 384x640 7 Lateral_lying_lefts, 2 Lateral_lying_rights, 1 Standing, 4.6ms
Speed: 1.2ms preprocess, 4.6ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_092157.jpg: 384x640 7 Lateral_lying_lefts, 1 Lateral_lying_right, 1 Standing, 7.4ms
Speed: 1.8ms preprocess, 7.4ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_092517.jpg: 384x640 8 Lateral_lying_lefts, 1 Lateral_lying_right, 1 Standing, 8.9ms
Speed: 1.9ms preprocess, 8.9ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_092658.jpg: 384x640 7 Lateral_lying_lefts, 1 Lateral_lying_right, 1 Standing, 5.3ms
Speed: 1.6ms preprocess, 5.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_093018.jpg: 384x640 8 Lateral_lying_lefts, 1 Lateral_lying_right, 1 Standing, 5.4ms
Speed: 1.5ms preprocess, 5.4ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_093158.jpg: 384x640 8 Lateral_lying_lefts, 2 Lateral_lying_rights, 1 Standing, 8.2ms
Speed: 1.6ms preprocess, 8.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_093518.jpg: 384x640 5 Lateral_lying_lefts, 1 Lateral_lying_right, 3 Standings, 1 Sternal_lying, 5.2ms
Speed: 1.5ms preprocess, 5.2ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_093658.jpg: 384x640 7 Lateral_lying_lefts, 1 Lateral_lying_right, 2 Standings, 7.4ms
Speed: 1.5ms preprocess, 7.4ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_094018.jpg: 384x640 4 Lateral_lying_lefts, 2 Lateral_lying_rights, 3 Standings, 2 Sternal_lyings, 8.2ms
Speed: 1.7ms preprocess, 8.2ms inference, 2.9ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_094159.jpg: 384x640 4 Lateral_lying_lefts, 2 Lateral_lying_rights, 2 Standings, 1 Sternal_lying, 7.4ms
Speed: 1.7ms preprocess, 7.4ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_094519.jpg: 384x640 4 Lateral_lying_lefts, 1 Lateral_lying_right, 3 Standings, 4 Sternal_lyings, 11.0ms
Speed: 1.7ms preprocess, 11.0ms inference, 2.6ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_094659.jpg: 384x640 3 Lateral_lying_lefts, 1 Lateral_lying_right, 5 Standings, 1 Sternal_lying, 8.5ms
Speed: 1.7ms preprocess, 8.5ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_095019.jpg: 384x640 2 Lateral_lying_lefts, 2 Lateral_lying_rights, 4 Standings, 2 Sternal_lyings, 7.9ms
Speed: 1.8ms preprocess, 7.9ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_095159.jpg: 384x640 3 Lateral_lying_lefts, 2 Lateral_lying_rights, 3 Standings, 2 Sternal_lyings, 10.1ms
Speed: 1.5ms preprocess, 10.1ms inference, 2.4ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_095519.jpg: 384x640 4 Lateral_lying_lefts, 5 Standings, 1 Sternal_lying, 8.5ms
Speed: 1.5ms preprocess, 8.5ms inference, 2.2ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_095700.jpg: 384x640 1 Lateral_lying_right, 1 Sitting, 6 Standings, 3 Sternal_lyings, 6.1ms
Speed: 1.6ms preprocess, 6.1ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_100020.jpg: 384x640 2 Lateral_lying_lefts, 2 Lateral_lying_rights, 1 Sitting, 4 Standings, 1 Sternal_lying, 6.1ms
Speed: 1.4ms preprocess, 6.1ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_100200.jpg: 384x640 4 Lateral_lying_lefts, 2 Lateral_lying_rights, 3 Standings, 1 Sternal_lying, 9.8ms
Speed: 1.4ms preprocess, 9.8ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

image 1/1 E:\multiview_pig_posture_recognition\train1_images\pen2_tur_cam1_20250209_100521.jpg: 384x640 2 Lateral_lying_lefts, 3 Lateral_lying_rights, 1 Sitting, 3 Standings, 1 Sternal_lying, 5.3ms

In [30]:
    gt_df = test_df[test_df["image_id"] == image_id]

    gt_boxes = []

    for _,row in gt_df.iterrows():

        x1 = row["x"]
        y1 = row["y"]
        x2 = row["x"] + row["w"]
        y2 = row["y"] + row["h"]

        gt_boxes.append([x1,y1,x2,y2])

In [31]:
    for pred in pred_boxes:
        best_iou = 0
        for gt in gt_boxes:
            iou = compute_iou(pred, gt)
            best_iou = max(best_iou, iou)
        ious.append(best_iou)

In [32]:
import numpy as np
mean_iou = np.mean(ious)
print("Mean IoU:", mean_iou)

Mean IoU: 0.8747141